### ISSUE TITLE
Connect wallet can't detect if no wallet is installed on the browser

### ISSUE THREAD

**Issue by ckaraca** [littlefish-foundation/littlefish-mvp#2]
Connect wallet button is unresponsive when Nami wallet is not installed on the browser.

An error should be thrown in this case:
"You need to install Nami wallet browser extension to use it in littlefish: https://app.littlefish.foundation/wallet"

**Comment by Nald97** [comment]
<img width="1438" alt="Screen Shot 2022-09-04 at 01 21 18" src="https://user-images.githubusercontent.com/70485619/188289327-9cb1116b-7553-49ad-8f14-8cfbd5535e62.png">

<img width="1440" alt="Screen Shot 2022-09-04 at 01 16 11" src="https://user-images.githubusercontent.com/70485619/188289331-351b532f-d212-4082-b58e-0d0c52c20231.png">

Thankyou for pointing it out :)

**Comment by Nald97** [comment]
@ckaraca Thank you for pointing it out. :) 

<img width="1438" alt="Screen Shot 2022-09-04 at 01 21 18" src="https://user-images.githubusercontent.com/70485619/188289386-26824cba-1e55-4083-a765-90d22b8045c5.png">

<img width="1440" alt="Screen Shot 2022-09-04 at 01 16 11" src="https://user-images.githubusercontent.com/70485619/188289391-3fdd453e-9f5f-423d-af22-fdb3ba5f7d8e.png">

**Comment by ckaraca** [comment]
Great work! thank you Donald
